version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: transportconnect-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: transportconnect
    volumes:
      - mongodb_data:/data/db
    networks:
      - transportconnect-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: transportconnect-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/transportconnect?authSource=admin
      JWT_SECRET: your_production_jwt_secret_here
      CLIENT_URL: http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - transportconnect-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: transportconnect-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:5000
    depends_on:
      - backend
    networks:
      - transportconnect-network
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongodb_data:

networks:
  transportconnect-network:
    driver: bridge